project_id = "tyorpbzvjnasyaqbggcp"

[functions.send-marketing-email]
verify_jwt = true

[functions.send-scheduled-marketing-emails]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = true

[functions.send-gift-notification]
verify_jwt = true

[functions.resend-gift-reminders]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.send-feedback-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.send-gift-email]
verify_jwt = true

[functions.process-gift-shipping]
verify_jwt = true

[functions.sync-reviews]
verify_jwt = false

[functions.receive-review]
verify_jwt = false

[functions.get-user-reviews]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = true
