project_id = "tyorpbzvjnasyaqbggcp"

[functions.send-marketing-email]
verify_jwt = true

[functions.send-scheduled-marketing-emails]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = true

[functions.send-gift-notification]
verify_jwt = true

[functions.resend-gift-reminders]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.send-feedback-email]
verify_jwt = true
